### PR TITLE
Fix Harvard dates, fixes #467

### LINKED ISSUE #467: Date parsing error on Harvard SCW collection
Many records in the Harvard Stuart Cary Welch collection parse fine but some return the following error:
```
ERROR Unexpected error on record <record #1 (data/harvard/scw/data/scw-1112.xml #1), output_id:harvard_scw-1112>
    while executing (to_field "cho_date_range_norm" at traject_configs/harvard_scw_config.rb:50)
...
   Exception: ArgumentError: comparison of String with 2022 failed
    /usr/local/bundle/gems/parse_date-0.4.2/lib/parse_date.rb:59:in `>'

[ERROR] comparison of String with 2022 failed
/usr/local/bundle/gems/parse_date-0.4.2/lib/parse_date.rb:59:in `>': comparison of String with 2022 failed (ArgumentError)
	from /usr/local/bundle/gems/parse_date-0.4.2/lib/parse_date.rb:59:in `year_range_valid?'
	from /usr/local/bundle/gems/parse_date-0.4.2/lib/parse_date.rb:76:in `range_array'
	from /opt/traject/lib/macros/date_parsing.rb:347:in `range_array'
	from /opt/traject/lib/macros/date_parsing.rb:306:in `range_from_mods_date_element'
	from /opt/traject/lib/macros/date_parsing.rb:273:in `block in harvard_mods_date_range'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer/step.rb:140:in `block in execute'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer/step.rb:135:in `each'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer/step.rb:135:in `execute'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer.rb:472:in `block (2 levels) in map_to_context!'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer.rb:512:in `handle_mapping_errors'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer.rb:471:in `block in map_to_context!'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer.rb:465:in `each'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer.rb:465:in `map_to_context!'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/indexer.rb:590:in `block (3 levels) in process'
	from /usr/local/bundle/gems/traject-3.3.0/lib/traject/thread_pool.rb:123:in `block in maybe_in_thread_pool'
	from /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	from /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	from /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	from /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	from /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	from /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```
The records that fail are not noticeably different from the ones that pass so I'm not sure what the issue is. To duplicate the error run:
```
docker run --rm -e SKIP_FETCH_DATA=true -v $(pwd)/.:/opt/traject -v $(pwd)/../dlme-metadata:/opt/traject/data -v $(pwd)/output:/opt/traject/output suldlss/dlme-transform:latest harvard/scw/data/scw-1112.xml
```

### PR DESCRIPTION
**Pull request by jacobthill**
## Why was this change made?

Some of the dates were not parsing correctly because the format could not be converted to an integer. This fixes that.

## Was the documentation (README, API, wiki, ...) updated?

- n/a

### CODE REVIEW

File: lib/macros/date_parsing.rb [hunk 1]
```diff
@@ -270,8 +270,21 @@ def mods_date_range
     #   looks in each element flavor for specific attribs to get best representation of date range
     def harvard_mods_date_range
       lambda do |record, accumulator, context|
-        range = range_from_mods_date_element('mods:dateCreated', record, context)
-        accumulator.replace(range) if range
+        start_year = record.xpath("#{ORIGIN_INFO_PATH}/mods:dateCreated[@point='start']", MODS_NS)&.first&.content
```
Comment (aaron-collier) [inline lib/macros/date_parsing.rb]: This change is causing the test failure at https://github.com/sul-dlss/dlme-transform/blob/master/spec/lib/traject/macros/date_parsing_spec.rb#L433. By not including the `point` attribute in the test case, the transform returns empty. The `point` attribute referenced here is accurate (you can see it in the data here: https://github.com/sul-dlss/dlme-metadata/blob/master/harvard/scw/data/scw-100.xml) so you'll need to update `date_parsing_spec.rb` accordingly.
