### PR TITLE
prevent IR arrays from having duplicate values, warn if dupes are detected

### LINKED ISSUE #677: Test arrays in IR for duplicate values
As the DLME data manager I need to ensure that no records are loaded with duplicate values in any field. Most fields contain hashes with language keys and arrays as values (e.g. `"cho_title":{"en":["Incipit Page with Illuminated Headpiece"]}`). Some fields contain only arrays (e.g. `"cho_identifier":["W.651.1B","W6511B"]`). In all cases, the values in the array should be testes to ensure that no two values are identical.

Requirements:
- [ ] Fails if duplicate values found in any array; the transform process will stop and an error message with problematic field, values, and dlme_source_file will be reported to the terminal.

### PR DESCRIPTION
**Pull request by jmartin-sul**
## Why was this change made?

closes #677

## How was this change tested?

* unit testing
* manual testing on laptop:
```sh
dlme-transform % exe/transform -w # i had only the aims data in my data dir, and i duplicated the title on the record in aims-9.xml
...snip...
W, [2021-07-15T17:52:11.129363 #24248]  WARN -- : traject_configs/aims_config.rb: key=cho_title; values=["Entretien avec Dr. Khadija Mohsen-Finan sur son dernier livre : Les Dissidents du Maghreb depuis les Independences", "Entretien avec Dr. Khadija Mohsen-Finan sur son dernier livre : Les Dissidents du Maghreb depuis les Independences"]; values array contains duplicates.  Check source data and/or traject config for errors.
{"cho_title":{"none":["Entretien avec Dr. Khadija Mohsen-Finan sur son dernier livre : Les Dissidents du Maghreb depuis les Independences"]},"cho_creator":{"en":["themaghribpodcast.com"]},"cho_date":{"en":["Wed, 24 Apr 2019 11:19:12 +0000"]},"cho_date_range_norm":[2019],"cho_date_range_hijri":[1440,1441],"cho_dc_rights":{"en":["Use of content for classroom purposes and on other non-profit educational websites is granted (and encouraged) with proper citation."]},"cho_description":{"none":["<p><strong><span style=\"font-family:'times new roman', times;font-size:14pt;\">Episode 63: Entretien avec Dr. Khadija Mohsen-Finan sur son dernier livre : Les Dissidents du Maghreb depuis les Independences</span></strong></p>\n<p style=\"text-align:justify;\"><span style=\"font-family:'times new roman', times;\">Dans ce podcast, Dr. Meriem Guetat , Directrice Adjointe du CEMAT, s’entretient avec Dr.  Khadija Mohsen-Finan sur son dernier livre <em>Les Dissidents du Maghreb depuis les Indépendences.</em></span></p>\n<p style=\"text-align:justify;\"><span style=\"font-family:'times new roman', times;\">L’ouvrage de Dr. Khadija Mohsen-Finan est l’un des premiers travaux post-2011 qui s’intéressent au concept de la dissidence à travers le Maghreb (Algérie, Maroc, Tunisie) et qui se base sur une recherche rétrospective de longue durée. </span></p>\n<p style=\"text-align:justify;\"><span style=\"font-family:'times new roman', times;\">Dans cet episode, Dr. Mohsen-Finan souligne l’importance d’étudier l’histoire du Maghreb à travers le prisme de la dissidence, tout courants idéologiques confondus, ce qui constitue un renversement de la perspective traditionnelle de recherche se concentrant exclusivement sur le pouvoir. Selon Dr. Mohsen-Finan, il s’agit d’aborder une histoire méconnue du Maghreb qui permet de comprendre ses diffrentes évoultions historiques mais aussi d’interprèter et d’imaginer les développements politiques futures dans la région. </span></p>\n<p style=\"text-align:justify;\"><span style=\"font-family:'times new roman', times;\">Lors de cette conversation, Dr. Mohsen-Finan a été invitée à répondre à un nombre de questions s’articulant autour des thèmes suivant :</span></p>\n<ul style=\"text-align:justify;\"><li><span style=\"font-family:'times new roman', times;\">    La définition de la notion de dissidence dans son ouvrage ainsi que le rapport du dissident au pouvoir. </span></li>\n<li><span style=\"font-family:'times new roman', times;\">    Les moments phares de l’histoire du Maghreb qui décrivent au mieux le rapport de lutte entre le pouvoir et ses opposants et ce en concentrant sur le  moment Youssefiste et de l’affaire Ahmed Ben Salah.</span></li>\n<li><span style=\"font-family:'times new roman', times;\">    Le groupe « perspectives » en Tunisie et l’évolution de ses relations avec le pouvoir. </span></li>\n<li><span style=\"font-family:'times new roman', times;\">    Le rôle des défenseurs des droits humains et le rôle joué par la LTDH dans l’analyse de la Tunisie.  </span></li>\n<li><span style=\"font-family:'times new roman', times;\">    Le printemps noir de Kabylie dans le cadre de la dissidence post-2011 et le rôle des minorités ethniques et linguistiques pour la compréhension de la notion de dissidence. </span></li>\n</ul><p style=\"text-align:justify;\"><span style=\"font-family:'times new roman', times;\">Dr. Khadija Mohsen-Finan est politologue spécialiste du Maghreb et du monde arabe, Docteur en sciences politiques (IEP Paris) et diplômée d’histoire (Université d’Aix-en-Provence). Actuellement enseignante et chercheure à l’Université de Paris 1 - Panthéon Sorbonne (laboratoire SIRICE), elle enseigne parallèlement à l’Université Ca’Foscari de Venise. Elle contribue également au comité de rédaction et à l’animation du journal en ligne Orient XXI.</span></p>\n<p style=\"text-align:justify;\"><span style=\"font-family:'times new roman', times;\">Cet épisode a été enregistré le 21 février 2019 au <a href=\"https://www.cematmaghrib.org/\">Centre d'Études Maghrébines à Tunis</a> (<a href=\"https://www.facebook.com/cematmaghrib/?ref=br_rs&\">CEMAT</a>) et s'inscrit dans le cadre du cycle de conférences <em><a href=\"https://www.themaghribpodcast.com/p/contemporary-thoughts.html\">Pensées contemporaines</a></em>.<br></span></p>\n<div style=\"text-align:justify;\">\n<div>\n<div>\n<div>\n<div>\n<p><span style=\"font-family:times, 'times new roman', serif;\">Nous remercions notre ami Mohammed Boukhoudmi pour son interpretation de l'extrait de nouba, \"Dziriya,\" par Dr. Noureddine Saoudi pour l'introduction et la conclusion de ce podcast.</span></p>\n</div>\n</div>\n</div>\n</div>\n</div>\n<p style=\"text-align:justify;\"><span style=\"font-family:times, 'times new roman', serif;\">Posted by Hayet Lansari, Librarian, Outreach Coordinator, Content Curator (CEMA).</span></p>\n<p style=\"text-align:justify;\"> </p>"]},"cho_edm_type":{"en":["Sound"],"ar-Arab":["صوت"]},"cho_extent":{"en":["43:25"]},"cho_has_type":{"en":["Interviews"],"ar-Arab":["المقابلات"]},"agg_data_provider":{"en":["The American Institute for Maghrib Studies"],"ar-Arab":["المعهد الأمريكي لدراسات المغرب"]},"agg_data_provider_country":{"en":["Morocco","Algeria","Tunisia"],"ar-Arab":["تونس","الجزائر","المغرب"]},"agg_provider":{"en":["The American Institute for Maghrib Studies"],"ar-Arab":["المعهد الأمريكي لدراسات المغرب"]},"agg_provider_country":{"en":["Morocco","Algeria","Tunisia"],"ar-Arab":["تونس","الجزائر","المغرب"]},"cho_type_facet":{"en":["Sound","Sound:Interviews"],"ar-Arab":["صوت","صوت:المقابلات"]},"id":"themaghribpodcast.podbean.com/entretien-avec-dr-khadija-mohsen-finan-sur-son-dernier-livre-les-dissidents-du-maghreb-depuis-les-independences-71f426608ed1c2498c75bf967549f13c","transform_version":"09a3bb7","transform_timestamp":"2021-07-15 17:52:11 -0700","agg_data_provider_collection":"aims/data","agg_is_shown_at":{"wr_id":"https://themaghribpodcast.podbean.com/e/entretien-avec-dr-khadija-mohsen-finan-sur-son-dernier-livre-les-dissidents-du-maghreb-depuis-les-independences/"},"agg_preview":{"wr_id":"https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog1668744/Khadija_Mohsen-Finan-_size.png"}}
```

### CODE REVIEW

**Comment by jmartin-sul** [comment]
had a few questions about whether more work was needed, which i paired w/ @aaron-collier on:
* are we ok w/ the rubocop exception for the modified method in the PR?  we think so, because it's kind of a pain to extract the array de-duping and logging code to a helper method in `EachRecord`, because it's being used from a lambda (seems like variable declarations get pulled into the lamba's scope just fine, but method references didn't work quite the same -- we decided it wasn't worth more debugging time)
* are we ok with just adding the unit tests?  yes, we think we're fine with the combo of the new unit tests, and the existing integration tests for catching regressions
* any need for further validation, e.g. some validation in `Contracts::CHO`?  nope, we think what's here should suffice.

ready for review, taking out of draft...

File: lib/macros/each_record.rb [hunk 1]
```diff
@@ -8,15 +8,33 @@ module EachRecord
...
+      config_file_path = caller_locations(1, 1).first.path
+
       lambda do |_record, context|
         context.output_hash.select { |key, _values| fields.include?(key) }.each do |key, values|
           result = Hash.new { [] }
 
-          values.each do |value|
+          unique_values = values.uniq
+          unless unique_values.length == values.length
+            ::DLME::Utils.logger.warn("#{config_file_path}: key=#{key}; values=#{values}; values array contains duplicates.  "\
```
Comment (aaron-collier) [inline lib/macros/each_record.rb:24]: This is an excellent addition :+1:

**Review by aaron-collier — APPROVED** [review]
