### PR TITLE
apply schema validation changes to all remaining fields, fixes #…

### LINKED ISSUE #336: Add dry schema validation for language tags on additional fields
Assign language tags and validation for:

- [ ] 'cho_edm_type'
- [ ] 'cho_has_type'
- [ ] 'cho_language'
- [x] 'cho_description'
- [ ] 'cho_date'
- [ ] 'cho_creator'
- [ ] 'cho_date_range_norm'
- [ ] 'cho_date_range_hijri'
- [ ] 'cho_dc_rights'
- [ ] 'cho_extent'
- [ ] 'cho_alternative'
- [ ] 'cho_contributor'
- [ ] 'cho_coverage'
- [ ] 'cho_format'
- [ ] 'cho_has_part'
- [ ] 'cho_is_part_of'
- [ ] 'cho_medium'
- [ ] 'cho_provenance'
- [ ] 'cho_publisher'
- [ ] 'cho_spatial'
- [ ] 'cho_temporal'
- [ ] 'cho_type'

### PR DESCRIPTION
**Pull request by jacobthill**
## Why was this change made?
Need to convert all metadata fields with text to hashes in order to store the language of the metadata as a key.

## Was the documentation (README, API, wiki, ...) updated?
n/a

### CODE REVIEW

File: traject_configs/bnf_common_config.rb [hunk 1]
```diff
@@ -61,4 +61,33 @@
...
 to_field 'agg_data_provider_country', data_provider_country_ar, lang('ar-Arab')
 
-each_record convert_to_language_hash('agg_data_provider', 'agg_data_provider_country', 'agg_provider', 'agg_provider_country', 'cho_title', 'cho_description')
+each_record convert_to_language_hash(
+  'agg_data_provider',
+  'agg_data_provider_country',
+  'agg_provider',
+  'agg_provider_country',
+  'cho_alternative',
+  'cho_contributor',
```
Comment (aaron-collier) [inline traject_configs/bnf_common_config.rb]: I think this may be an issue with duplication, cho_contributor, cho_creator, etc, were not in bnf_common originally. Have you determined that the hash output is OK?

**Comment by jacobthill** [comment]
@aaron-collier I'm not sure what changes you want? I fixed the duplication issues as far as I can tell. I fixed BnF and Stanford. Do you see other issues?
