### PR TITLE
Do not raise exceptions for any date-parsing errors

### LINKED ISSUE #325: Catch exception where first year > last year
The parse_date gem raises an error in this case, but for AUC (and likely other collection) we want to capture this error and log it as a warning in order to fix at the provider.

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #325

## Why was this change made?

Collect date-parsing errors as transformations run and then log them at the end of the run. This way, @jacobthill can see more clearly which datasets need changes, without bombing a whole batch.

Also includes:
* Bump `parse_date` to 0.4.2 so that year range exceptions come back as `ParseDate::Error` rather than `StandardError`.
* Rename `PostProcess` macros to `EachRecord` to distinguish them from the `after_processing` code
* Let integration specs fail if any exceptions are raised so we can find errors sooner as we go forward.

## Was the documentation (README, API, wiki, ...) updated?

No.

### CODE REVIEW

File: traject_configs/aims_config.rb [hunk 1]
```diff
@@ -4,13 +4,13 @@
 require 'macros/aims'
 require 'macros/date_parsing'
 require 'macros/dlme'
-require 'macros/post_process'
+require 'macros/each_record'
```
Comment (ndushay) [inline traject_configs/aims_config.rb]: so these should now be alphabetical.  (I know, I know - it's Jacob as much as me). requires and extends ...

Comment (mjgiarlo) [reply traject_configs/aims_config.rb]: done
